<div class="container inner">
	<div class="one_fourth">
		<a class="logo" href="#"><img <?php echo "src=\"" . $this->basePath() . "/img/logo.png\"" ?> alt="Eventis"></a>
		<br> <br>
		<p>Projet de mise en place d'un Système d'Information Médical National du Sénégal 
		financé par le Fond d'Impulsion pour la Recherche Scientifique et Technique (FIRST2011)</p>
	</div>
	<?php echo $this->archive?>
	<?php echo $this->categorie?>
	<?php echo $this->contact?>
</div>