<?php echo $this->doctype(); ?>

<html>
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle('SIMENS '.'Système d\'Information Médical National du Sénégal')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/simens_tabicon.ico'))
        				->prependStylesheet($this->basePath() . '/css/style.css')
        				->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/flexslider.css')
        				->prependStylesheet($this->basePath() . '/fancybox/jquery.fancybox-1.3.4.css')
                        ->prependStylesheet($this->basePath() . '/css/resp.css')
                        ->prependStylesheet($this->basePath() . '/css/reset.css')
        ?>
        
	<!--  <link rel="stylesheet" type="text/css" href="colorfa44.css?color=23dbdb" class="color"> -->

<!-- Scripts -->
        <?php echo $this->headScript()
        	->prependFile($this->basePath() . '/js/script.js')
            ->prependFile($this->basePath() . '/fancybox/jquery.fancybox-1.3.4.js')
        	->prependFile($this->basePath() . '/js/jquery.flexslider.js')
        	->prependFile($this->basePath() . '/js/retina.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/jquery.isotope.min.js')
            ->prependFile($this->basePath() . '/js/portfolio.js')
        ; ?>


</head>
<body>
	<div id="wrap">
		<header>
			<div id="header-bar">
				<div id="header-bar-content">
					<div class="inner">

						<ul id="socials">
							<form></form>
							<form>
								<label for="contact-name">Identifiant:</label> <input
									type="text" id="contact-name" name="identifiant"> <label
									for="contact-email">Password</label> <input type="text"
									id="contact-email" name="pass" spellcheck="false"> <input
									type="submit" id="contact-submit" value="OK" class="button">
							</form>

						</ul>
						<div class="clear"></div>
					</div>
				</div>
				<div id="header-bar-handle"></div>
			</div>
			<div class="inner relative">
				<a <?php echo "href=\"" . $this->basePath() . "/actualite\""?>><img <?php echo "src=\"" . $this->basePath() . "/img/logo.png\"" ?> alt="simens"></a> <a
					id="menu-toggle" class="button dark" href="#"><i
					class="icon-reorder"></i></a>
				<nav id="navigation">
					<form id="search">
						<input type="text" name="s" spellcheck="false">
					</form>
					<ul id="main-menu">
						<li class="current-menu-item"><a <?php echo "href=\"" . $this->basePath() . "/actualite\""?>>Actualités</a></li>
						<li class="parent"><a <?php echo "href=\"" . $this->basePath() . "/maladie\""?>>Maladies</a>
							<ul class="sub-menu">
								<li><a href="">Type 1</a></li>
								<li><a href="">Type 2</a></li>
								<li><a href="">Type 3</a></li>
								<li><a class="parent" href="#">Type 4</a>
									<ul class="sub-menu">
										<li><a href="">Sous Type 1</a></li>
										<li><a href="">Sous Type 2</a></li>
										<li><a href="">Sous Type 3</a></li>
									</ul></li>
							</ul></li>
						<li class="parent"><a <?php echo "href=\"" . $this->basePath() . "/bonnepratique\""?>>Bonnes Pratiques</a>
							<ul class="sub-menu">
								<li><a href="">Alimentaires</a></li>
								<li><a href="">Hygiénique</a></li>
								<li><a href="">Physiques</a></li>
								<li><a href="">Diverses</a></li>
							</ul></li>
						<li class="menu-item"><a href="#">Forum de discussions</a>
						<li class="parent"><a <?php echo "href=\"" . $this->basePath() . "/presentation/presentation/resume\""?>>Le projet SIMENS</a>
							<ul class="sub-menu">
								<li><a <?php echo "href=\"" . $this->basePath() . "/presentation/presentation/resume\""?>>Résumé</a></li>
								<li><a <?php echo "href=\"" . $this->basePath() . "/presentation/presentation/financement\""?>>Financement</a></li>
								<li><a <?php echo "href=\"" . $this->basePath() . "/presentation/presentation/contributeurs\""?>>Contributeurs</a></li>
								<li><a <?php echo "href=\"" . $this->basePath() . "/presentation/presentation/partenaires\""?>>Partenaires</a>
								<li><a <?php echo "href=\"" . $this->basePath() . "/presentation/presentation/contact\""?>>Contact</a></li>
							</ul></li>
					</ul>
				</nav>
				<div class="clear"></div>
			</div>
		</header>
		<?php echo $this->bloghead; ?>
		<div id="content" class="right-sidebar">
			<div class="inner">
				<div id="main" role="main">
					<?php echo $this->content; ?>
				</div>
					<?php echo $this->blogrightsidebar?>
			</div>
			<div class="clear"></div>
		</div>
		<?php echo $this->blogarticlepagination?>
		<footer class="dark">
			<?php echo $this->blogfooter?>
			<div id="footer-bar">
				<div class="inner container">
					<div class="one_half">
						<p>&copy; 2011 - <?php echo date('Y') ?> - Projet SIMENS/UFR SAT/UGB - Tous les droits réservés.</p>
					</div>
					<div class="one_half">
						<ul>
							<li><a href="#">Terms</a></li>
							<li><a href="#">Privacy</a></li>
							<li><a href="#">Contact</a></li>
						</ul>
					</div>
				</div>
			</div>
		</footer>
	</div>
</body>
</html>