<div class="one_fourth">
	<h3>Catégories</h3>
	<ul class="link-list">
		<li><a <?php echo "href=\"" . $this->basePath() . "/presentation/resume\""?>><text id='resume'>Résumé</text></a></li>
		<li><a <?php echo "href=\"" . $this->basePath() . "/presentation/financement\""?>><text id='financement'>Financement</text></a></li>
		<li><a <?php echo "href=\"" . $this->basePath() . "/presentation/contributeurs\""?>><text id='contributeurs'>Contributeurs</text></a></li>
		<li><a <?php echo "href=\"" . $this->basePath() . "/presentation/partenaires\""?>><text id='partenaires'>Partenaires</text></a></li>
		<li><a <?php echo "href=\"" . $this->basePath() . "/presentation/contact\""?>><text id='contact'>Contact</text></a></li>
	</ul>
</div>