<div class="one_fourth">
	<h3>Catégories</h3>
	<ul class="link-list">
		<li><a href="<?php echo $this->basePath() . '/presentation/resume'?>" >Type 1</a></li>
		<li><a href="<?php echo $this->basePath() . '/presentation/resume'?>" >Type 2</a></li>
		<li><a href="<?php echo $this->basePath() . '/presentation/resume'?>" >Type 3</a></li>
		<li><a href="<?php echo $this->basePath() . '/presentation/resume'?>" >Type 4</a></li>
	</ul>
</div>