<div class="one_fourth contacts">
	<h3>Contacts</h3> 
		<img style="float: left;" <?php echo "src=\"" . $this->basePath() . "/img/phone-icon.png\"" ?> alt=""> <span style="float: left; margin-top: 10px;" class="phone-number"> : (+221) 00-000-00-00</span>
 	    <div class="space"></div>
		
		<img style="float: left;" <?php echo "src=\"" . $this->basePath() . "/img/email-icon.png\"" ?> alt=""> <span style="float: left; margin-top: 10px;" class="email-address"> <a href="mailto:simens@ugb.edu.sn"> : contact@simens.sn</a></span>
</div>