<?php echo $this->doctype(); ?>

<html>
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle('SIMENS '.'Système d\'Information Médical National du Sénégal')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/simens_tabicon.ico'))
        				->prependStylesheet($this->basePath() . '/css/style.css')
        				->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/flexslider.css')
        				->prependStylesheet($this->basePath() . '/fancybox/jquery.fancybox-1.3.4.css')
                        ->prependStylesheet($this->basePath() . '/css/resp.css')
                        ->prependStylesheet($this->basePath() . '/css/reset.css')
        ?>
        
        <!-- Scripts -->
        <?php echo $this->headScript()
        	->prependFile($this->basePath() . '/js/script.js')
            ->prependFile($this->basePath() . '/fancybox/jquery.fancybox-1.3.4.js')
        	->prependFile($this->basePath() . '/js/jquery.flexslider.js')
        	->prependFile($this->basePath() . '/js/retina.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/jquery.isotope.min.js')
            ->prependFile($this->basePath() . '/js/portfolio.js')
        ; ?>


</head>
<body>
	<div id="wrap">
		<header>
			<div id="header-bar">
			</div>
			
			<div class="inner relative"> 
				<a <?php echo "href=" . $this->basePath();?> ><img <?php echo "src=\"" . $this->basePath() . "/img/logo.png\"" ?> alt="simens"></a> <a
					id="menu-toggle" class="button dark" href="#"><i
					class="icon-reorder"></i></a>
				<nav id="navigation">
					<form id="search">
						<input type="text" name="s" spellcheck="false">
					</form>
					<ul id="main-menu">
						<li class="current-menu-item"><a  href="<?php echo $this->basePath();?>" > Actualités</a></li>
						<li class="parent"><a href="<?php echo $this->basePath().'/maladie';?>" > Maladies</a>
							<ul class="sub-menu">
							    <?php if($this->layout()->user['role_personne'] == 'moderateur' ) {?>
								  <li><a href="<?php echo $this->basePath().'/maladie/liste-article-soumis';?>">
								      <img style="margin-right: 6px; float: left;" src="<?php echo $this->basePath().'/img/article/42_.png'; ?>">
								      Liste des articles
								    </a>
								  </li>
								<?php } ?>
								
								
								<?php if($this->layout()->user['role_personne'] == 'redacteur' ) {?>
								  <li><a href="<?php echo $this->basePath().'/maladie/liste-article';?>">
								      <img style="margin-right: 6px; float: left;" src="<?php echo $this->basePath().'/img/article/42_.png'; ?>">
								      Liste des articles
								    </a>
								  </li>
								  <li><a href="<?php echo $this->basePath().'/maladie/redaction-article';?>">
								      <img style="margin-right: 6px; float: left;" src="<?php echo $this->basePath().'/img/article/44_.png'; ?>">
								      Nouvel article
								    </a>
								  </li>
								<?php } ?>
								
								
								<li><a href="">Type 1</a></li>
								<li><a class="parent" href="#">Type 2</a>
									<ul class="sub-menu">
										<li><a href="">Sous Type 1</a></li>
										<li><a href="">Sous Type 2</a></li>
										<li><a href="">Sous Type 3</a></li>
									</ul></li>
							</ul>
						</li>
						<li class="parent"><a href="<?php echo $this->basePath();?>" > Bonnes Pratiques</a>
							<ul class="sub-menu">
								<li><a href="">Alimentaires</a></li>
								<li><a href="">Hygiénique</a></li>
								<li><a href="">Physiques</a></li>
								<li><a href="">Diverses</a></li>
							</ul>
						</li>
						<li class="menu-item"><a href="#">Forum de discussions</a>
						</li>
						<li class="parent"><a href="<?php echo $this->basePath().'/presentation/resume';?>" > Le projet SIMENS</a>
							 <ul class="sub-menu">
								<li><a <?php echo "href=\"" . $this->basePath() . "/presentation/resume\"" ?>>Résumé</a></li>
								<li><a <?php echo "href=\"" . $this->basePath() . "/presentation/financement\""?>>Financement</a></li>
								<li><a <?php echo "href=\"" . $this->basePath() . "/presentation/contributeurs\""?>>Contributeurs</a></li>
								<li><a <?php echo "href=\"" . $this->basePath() . "/presentation/partenaires\""?>>Partenaires</a>
								<li><a <?php echo "href=\"" . $this->basePath() . "/presentation/contact\""?>>Contact</a></li>
							 </ul>
						</li>
					</ul>
				</nav>
				<div class="clear"></div>
			</div>
		</header>
		
		
		<!-- ************ GESTION DES IMAGES DEFILANTES *********** -->
		<!-- ************ GESTION DES IMAGES DEFILANTES *********** -->
		<!-- ************ GESTION DES IMAGES DEFILANTES *********** -->
		<!-- ************ GESTION DES IMAGES DEFILANTES *********** -->
		<?php $imagesDefilantes = $this->layout()->imagesDefilantes; ?>
		
		<div class="EmplacementLayoutImagesDefilantes">
		  
		  <div id="slider" class="flexslider">
		    <ul class="slides">
				
				<?php for($i = 0 ; $i < count($imagesDefilantes) ; $i++) { ?>
				   <li><img  src="<?php echo $this->basePath() . '/img/blog/'.$imagesDefilantes[$i]['image'].'.jpg'; ?>" />
					 <div class="inner">
					   <h2 class="flex-caption" style="bottom: 60px;"> <?php echo $imagesDefilantes[$i]['titre_1']; ?> </h2>
					   <h3 class="flex-caption" style="bottom: 20px;"> <?php echo $imagesDefilantes[$i]['titre_2']; ?> </h3>
					 </div>
				   </li>
				<?php } ?>
				
			</ul>
		  </div>
		  
		</div>
		
		<script type="text/javascript">
		   $(window).load(function(){
				$('.flexslider').flexslider({
					controlNav: false,
					animation: "slide",
					start: function(slider){
    					$('body').removeClass('loading');
					}	
				});
		   });
		</script>
		
		<!-- ************ FIN FIN GESTION DES IMAGES DEFILANTES *********** -->
		<!-- ************ FIN FIN GESTION DES IMAGES DEFILANTES *********** -->
		<!-- ************ FIN FIN GESTION DES IMAGES DEFILANTES *********** -->
		
		
		
		<?php echo $this->outilsutilisateurs; ?>
		<div id="content" class="right-sidebar2">
			<div class="innerAccueil">
				<div id="main2">
					<?php echo $this->content; ?>
				</div>
					<?php echo $this->blogrightsidebar?>
			</div>
			<div class="clear"></div>
		</div>
		
		
		
		
		
		<footer class="dark">
			<div class="container inner">
				<div class="one_fourth">
					<a class="logo" href="#"><img <?php echo "src=\"" . $this->basePath() . "/img/logo.png\"" ?> alt="Eventis"></a>
					<br> <br>
					<p>Projet de mise en place d'un Système d'Information Médical National du Sénégal 
		               financé par le Fond d'Impulsion pour la Recherche Scientifique et Technique (FIRST2011)</p>
				</div>
				<div class="one_fourth">
					<h3>Archive</h3>
					<ul class="link-list">
						<li><a href="#">November 2013</a></li>
						<li><a href="#">December 2012</a></li>
						<li><a href="#">Janurary 2013</a></li>
						<li><a href="#">February 2014</a></li>
					</ul>
				</div>
				<div class="one_fourth">
	                <h3>Catégories</h3>
	                <ul class="link-list">
		                <li id="a1"><a href="<?php echo $this->basePath() . '/actualite'; ?>" > Actualités</a></li>
		                <li id="a2"><a href="<?php echo $this->basePath() . '/actualite'; ?>" > Maladies</a></li>
		                <li id="a3"><a href="<?php echo $this->basePath() . '/actualite'; ?>" > Bonnes Pratiques</a></li>
		                <li id="a4"><a href="<?php echo $this->basePath() . '/actualite'; ?>" > Forum de discussions</a></li>
   		                <li id="a5"><a href="<?php echo $this->basePath() . '/presentation/resume'; ?>" > Le projet SIMENS</a></li>
	                </ul>
                </div>
				<div class="one_fourth contacts">
	            
	            <img style="float: left;" <?php echo "src=\"" . $this->basePath() . "/img/phone-icon.png\"" ?> alt=""> <span style="float: left; margin-top: 10px;" class="phone-number"> : (+221) 00-000-00-00</span>
 	            <div class="space"></div>
		
		        <img style="float: left;" <?php echo "src=\"" . $this->basePath() . "/img/email-icon.png\"" ?> alt=""> <span style="float: left; margin-top: 10px;" class="email-address"> <a href="mailto:simens@ugb.edu.sn"> : contact@simens.sn</a></span>
				
				</div>
			</div>
			
			<div id="footer-bar">
				<div class="inner container">
					<div class="one_half">
						<span>&copy; Copyright 2015 <a href="#">simens</a>. Ufr sat etc
						</span>
					</div>
					<div class="one_half">
						<ul>
							<li><a href="#">Terms</a></li>
							<li><a href="#">Privacy</a></li>
							<li><a href="#">Contact</a></li>
						</ul>
					</div>
				</div>
			</div>
			
		</footer>
	</div>
</body>
</html>
