<h2>Mots clés</h2>
<ul class="tags">
	<li><a href="#">CHRSL</a></li>
	<li><a href="http://www.sante.gouv.sn/index.php?option=com_content&view=category&layout=blog&id=114&Itemid=809">Ebola</a></li>
	<li><a href="http://www.sante.gouv.sn/">MSAS</a></li>
	<li><a href="http://www.recherche.gouv.sn">FIRST</a></li>
	<li><a href="http://www.seysoo.com">SeySoo</a></li>
	<li><a href="http://www.simens.sn">SIMENS</a></li>
	<li><a href="http://www.uadb.edu.sn">UADB</a></li>
	<li><a href="http://www.ugb.sn">UGB</a></li>
</ul>