<style>
#contact,#p5 a{ color: #49afcd; }
</style>
<div class="container inner">
	<h1><?php echo $this->subheadtitle?></h1>
	<br>
	<p class="articletext"><span style = "font-weight: bold; text-decoration: underline;">Nom de contact :</span> Pr Moussa Lo, Université Gaston Berger de Saint-Louis</p>
	<p class="articletext"><span style = "font-weight: bold; text-decoration: underline;">Téléphone :</span> (+221) 33-961-23-40</p>
	<p class="articletext"><span style = "font-weight: bold; text-decoration: underline;">Email :</span> <a href="mailto:contact@simens.sn">contact@simens.sn</a></p>
	<p class="articletext"><span style = "font-weight: bold; text-decoration: underline;">Adresse postale :</span> UFR SAT, Université Gaston Berger, B.P. 234 Saint-Louis, Sénégal</p>
</div>