<style>
#financement,#p2 a{ color: #49afcd; }
</style>
<div class="container inner">
	<h1><?php echo $this->subheadtitle?></h1>
	<br>
	<p class="articletext">
		Le projet SIMENS est en ce moment soutenu par le Ministère de l'Enseignement Supérieur et de la Recherche (MESR) 
		au travers du Fond d'Impulsion pour la Recherche Scientifique et Technique (FIRST2011).
		Le projet est conduit par l'Unité de Formation et de Recherche (UFR) des Sciences Appliquées et Technologie (SAT)
		de l'Université Gaston Berger (UGB) de Saint-Louis. Il est mis en oeuvre en étroite collaboration avec l'UFR des Sciences de la Santé (2S)
		et le Centre Hospitalier Régional de Saint-Louis (CHRSL). 
	</p>
</div>