<style>
#resume,#p1 a{ color: #49afcd; }
</style>
<div class="container inner">
	<h1><?php echo $this->subheadtitle?></h1>
	<br>
	<p class="articletext">
		La gestion des informations au sein des organisations a connu une mutation fulgurante grâce à l’avènement des technologies de l’information et de la communication (TIC). Des secteurs comme les grandes distributions, le secteur privé de manière générale, se sont très tôt doté de robustes systèmes d’information (SI) leur permettant de gérer et tirer profit de la valeur de l’information.
	</p>
	<p class="articletext">
		Cependant, le secteur public de la santé est en retard dans cette nouvelle tendance innovante des TIC. 
		Or, de grandes quantités d’informations sont produites quotidiennement par les activités médicales tels que les consultations, les comptes rendus d’hospitalisation, les rapports d’analyse de laboratoire et de causes de décès, etc. 
		Ces informations sont consignées dans des documents essentiellement textuels, des images et des dossiers dont le mode d’accès  et d’exploitation se font principalement de manière manuelle. 
		Néanmoins, certaines structures sanitaires disposent de leurs propres applications leur permettant de gérer leurs patients, leurs rendez-vous, leur paiement, etc. sans possibilité de partager ces informations et de communiquer avec d’autres systèmes. 
		Ces informations sont difficiles à réutiliser et à partager du fait de leur hétérogénéité structurelle.
	</p>
	<p class="articletext">
		C’est ainsi que nous avons proposé en 2011 un projet de mise en place d’un sys-tème d’information médical national pour le Sénégal (SIMENS) permettant de surmonter toutes ces difficultés. 
		Ce système devra permettre d’identifier de ma-nière unique un patient sur le plan national à travers son dossier médical informatisé et de conserver de manière structurée sur ordinateur toute sorte d’informations utiles recueillies durant les activités médicales. 
		Ces informations médicales pourront être partagées confidentiellement entre acteurs de la santé, et être exploitées pour des besoins d’alerte, de prévention, de suivi et de contrôle de phénomènes épidémiologiques. 
		La gestion de la confidentialité des données personnelles sur les patients, la structuration de ces informations et la rapidité de leur intégration à une échelle géographique supérieure (départementale, régionale, nationale) sont la clé de voute de la réussite de ce projet. 
	</p>
	<p class="articletext">
		Il est également prévue de gérer les informations sur les établissements de santé, le personnel médical notamment les spécialistes, les équipements matériels, la localisation géographique, etc. pour des besoins de recherche d’information.
	</p>
	<p class="articletext">
		SIMENS comprend principalement quatre modules :
			<li class="articletext">Gestion des activités médicales : consultation, diagnostic, hospitalisation, ren-dez-vous médical, analyse et examen médicaux, prescription médicamenteuse, etc.</li>
			<li class="articletext">Gestion du dossier patient : construction d’un dossier patient fondé sur un format standardisé de représentation numérique des données médicales du pa-tient au niveau national. Ainsi, le patient est identifié de façon unique et son historique sanitaire est exploité lors de son traitement (prise en compte de ses intolérances et allergies lors des prescriptions thérapeutiques) mais aussi pour son suivi sanitaire (gestion des mises à jour de ses vaccins par exemple).</li>
			<li class="articletext">Gestion administrative et financière : données administratives du patient, ges-tion du personnel médical et technique, facturation et paiement, pharmacie, stock et approvisionnement, naissances et décès, etc.</li>
			<li class="articletext">Portail web d’information : espace membre pour les patients et les profession-nels de santé, recherche de structures sanitaires (hôpital, clinique, laboratoire médical, etc.), système d’information géographique national (statistique, taux de prévalence des maladies, etc.)</li>
	</p>
	<p class="articletext">
		Au-delà de la gestion des tâches quotidiennes, nous développons aussi dans ce projet un système d'intégration de ces données médicales à une échelle supérieure (départementale, régionale et nationale) pour offrir une vue globale et des outils d'aide à la décision aux autorités sanitaires et politiques.
	</p>
	<p class="articletext"> 
		La figure ci-dessous montre l’architecture de base de SIMENS.
	</p>
	<p class="articletext">
		<img <?php echo "src=\"" . $this->basePath() . "/img/simens_architecture.png\""; ?> alt="Image manquante">
	</p>
</div>
